version: '2'
services:
  postgres-server:    
    image: postgres:latest
    container_name: zabbix-postgres
    restart: always
    environment:   
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata 
    ports:
      - 3306:3306
    networks:
        zabbix-network:
           ipv4_address: 172.10.0.3  


  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_JAVAGATEWAY: zabbix-java-gateway
      ZBX_STARTDISCOVERERS: 3
      ZBX_STARTVMWARECOLLECTORS: 1
      ZBX_VMWAREFREQUENCY: 60
      ZBX_VMWAREPERFFREQUENCY: 60
      ZBX_VMWARECACHESIZE: 8M
      ZBX_VMWARETIMEOUT: 10

    depends_on:
      - postgres-server
    ports:
      - 10051:10051	
    networks:
        zabbix-network:
            ipv4_address: 172.10.0.2  
    volumes:
      - zabbix-alertscripts:/usr/lib/zabbix/alertscripts
      - zabbix-externalscripts:/usr/lib/zabbix/externalscripts
      - zabbix-enc:/var/lib/zabbix/enc
      - zabbix-mibs:/var/lib/zabbix/mibs
      - zabbix-modules:/var/lib/zabbix/modules
      - zabbix-snmptraps:/var/lib/zabbix/snmptraps
      - zabbix-ssh_keys:/var/lib/zabbix/ssh_keys
      - zabbix-ssl-certs:/var/lib/zabbix/ssl/certs
      - zabbix-ssl-keys:/var/lib/zabbix/ssl/keys
      - zabbix-ssl-ssl_ca:/var/lib/zabbix/ssl/ssl_ca

  zabbix-web-nginx:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web-nginx
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_NAME: "Zabbix Labs"
      PHP_TZ: America/Bahia   
    
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - 4000:80
    volumes:
      - zabbix-web-data:/usr/share/zabbix
    networks:
        zabbix-network:
            ipv4_address: 172.10.0.4

  zabbix-server-agent:
      image: zabbix/zabbix-agent:latest
      restart: always
      container_name: zabbix-server-agent
      environment:
        ZBX_HOSTNAME: "Zabbix server"
        ZBX_SERVER_HOST: 172.10.0.2
        ZBX_SERVER_PORT: 10051
      depends_on:
        - zabbix-server
      ports:
        - 10050:10050
      networks:
            zabbix-network:
                ipv4_address: 172.10.0.5 

  grafana-xxl:  
       image: monitoringartist/grafana-xxl:latest
       restart: always
       container_name: grafana-xxl
       ports:
       - 3000:3000
       networks:
            zabbix-network:
                ipv4_address: 172.10.0.8

volumes: 
  zabbix-alertscripts:
  zabbix-externalscripts:
  zabbix-enc:
  zabbix-mibs:
  zabbix-modules:
  zabbix-snmptraps:
  zabbix-ssh_keys:
  zabbix-ssl-certs:
  zabbix-ssl-keys:
  zabbix-ssl-ssl_ca:
  zabbix-web-data:


networks:
   zabbix-network:
      ipam:
         config:
         - subnet: 172.10.0.0/16
           gateway: 172.10.0.1
